APP := "main"

default: build

build:
    riscv64-unknown-elf-gcc \
      -march=rv32i -mabi=ilp32 \
      -ffreestanding -nostdlib -static \
      -fno-pic -fno-pie \
      -fdata-sections -ffunction-sections \
      -Og \
      -g \
      -Wl,-T,link.ld \
      -Wl,--gc-sections \
      -Wall -Wextra \
      boot.s {{APP}}.c \
      -o {{APP}}.elf
    riscv64-unknown-elf-objcopy -O binary {{APP}}.elf {{APP}}.bin
    hexdump -v -e '1/4 "%08x\n"' {{APP}}.bin > {{APP}}.mi
    riscv64-unknown-elf-objdump --disassemble-all -S {{APP}}.elf > {{APP}}.disasm
    cp {{APP}}.mi rom.mi

install:
    cp rom.mi ../../rom.mi

clean:
    rm -f {{APP}}.elf {{APP}}.bin {{APP}}.mi {{APP}}.disasm rom.mi
