-d /Users/theilmann/Jahresarbeit/Prozessor/impl/gwsynthesis/Prozessor.vg
-p GW5A-25B-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cfg /Users/theilmann/Jahresarbeit/Prozessor/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 2
-route_option 1
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
