-d /Users/theilmann/Jahresarbeit/Praktischer Teil/Verilog/PMOD_Display/impl/gwsynthesis/PMOD_Display.vg
-p GW5A-25A-MBGA121N-1
-pn GW5A-LV25MG121NC1/I0
-cst /Users/theilmann/Jahresarbeit/Praktischer Teil/Verilog/PMOD_Display/src/PMOD_Display.cst
-cfg /Users/theilmann/Jahresarbeit/Praktischer Teil/Verilog/PMOD_Display/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
